spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: ${db_user}
    password: ${db_password}
stripe:
  apiUrl: https://api.stripe2.com
  enabled: true
  timeout: 2000
  supported-currencies: USD, EUR, NZD, GBP, CAD
payment-gateway: stripe
mail:
  host: 192.168.12.18
  port: 8082